# Generated by Django 4.2.6 on 2023-10-23 15:40

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('paid', True)), fields=['email'], name='email_paid_idx_btree'),
        ),
    ]
