# Generated by Django 4.2.6 on 2023-10-24 18:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_order_email_paid_idx_btree'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=django.contrib.postgres.indexes.GinIndex(fields=['status'], name='status_idx_gin'),
        ),
    ]
