# Generated by Django 4.2.6 on 2023-11-10 10:07

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_order_status_idx_gin'),
    ]
    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='order',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('paid', True)), fields=['email'], name='email_idx_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
